# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby on Rails CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  ruby-test:
    name: Ruby Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Backend
    
    services:
      postgres:
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        image: postgres:13
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare for Backend Tests
      run: |
        sudo apt-get -yqq install libpq-dev
    
    - name: Remove  Gemfile.lock
      run: |
        sudo rm Gemfile.lock
      if: github.event.pull_request.base.ref == 'master' || (contains(github.ref, 'master') && github.event_name == 'push')
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        bundler-cache: true
        working-directory: Backend
    
    - name: Yarn with caching
      uses: bahmutov/npm-install@HEAD
      with:
        working-directory: Backend
        
    - name: Build and Test
      env:
        RAILS_ENV: test
        PG_USER: postgres
        PG_PASSWORD: postgres
      run: |
        bundle exec rake db:create
        bundle exec rake db:migrate
        bundle exec rake test
        
    - name: Deploy API to heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        working-directory: Backend
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: "Backend"
      if: contains(github.ref, 'master') && github.event_name == 'push'
      
    - name: Deploy GA to heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        working-directory: Backend
        heroku_api_key: ${{ secrets.HEROKU_API_KEY_GA }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_GA }}
        heroku_email: ${{ secrets.HEROKU_EMAIL_GA }}
        appdir: "Backend"
      if: contains(github.ref, 'master') && github.event_name == 'push'
